# .terraform-docs.yml
content: |-
  ![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=for-the-badge&logo=terraform&logoColor=white) ![Maintainer](https://img.shields.io/badge/Built%20By-Bradley-brightgreen?style=for-the-badge&logo=terraform)
  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}
  
  ## Example enabling only compute

  ```hcl
  {{ include "example/example-1/main.tf" }}
  ```
  ---
  
  ## Example enabling a few API's 

  `main.tf`
  ```hcl
  {{ include "example/example-2/main.tf" }}
  ```
  
  `variables.tf`
  ```hcl
  {{ include "example/example-2/terraform.tfvars" }}
  ```