name: Create tag and release
on:
  push:
    branches:
      - main


permissions:
  pull-requests: write
  contents: write

jobs:
  create-tag-and-release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    name: Bump tag and cut release
    steps:
      - uses: actions/checkout@v4

      - name: Bumpr Create Tag
        id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bumpr.outputs.next_version }}
          name: Version ${{ steps.bumpr.outputs.next_version }}
          generate_release_notes: true
          body_path: CHANGELOG.md
          append_body: true
          draft: false
          prerelease: false
